import sinon from 'sinon';
import ViewHelpers from '../../../src/backend/utils/view-helpers/view-helpers';

const expectedResult = {
  recordActionUrl: '#recordActionUrl',
  resourceActionUrl: '#resourceActionUrl',
  bulkActionUrl: '#bulkActionUrl',
  forgotPasswordUrl: 'forgotPasswordUrl',
  changePasswordUrl: 'changePasswordUrl',
  signupUrl: 'signupUrl',
  loginUrl: 'loginUrl',
  logoutUrl: 'logoutUrl',
  impersonateUrl: 'impersonateUrl',
  impersonateLogoutUrl: 'impersonateLogoutUrl',
  rootUrl: 'admin',
  assetPath: 'assetPath',
  resourceUrl: 'resourceUrl',
  dashboardUrl: 'dashboardUrl',
  pageUrl: 'pageUrl',
  publicPageUrl: 'publicPageUrl',
  editUrl: 'editUrl',
  showUrl: 'showUrl',
  deleteUrl: 'deleteUrl',
  newUrl: 'newUrl',
  listUrl: 'listUrl',
  bulkDeleteUrl: 'bulkDeleteUrl',
};

export default (): ViewHelpers => ({
  options: {
    forgotPasswordPath: expectedResult.forgotPasswordUrl,
    signupPath: expectedResult.signupUrl,
    changePasswordPath: expectedResult.changePasswordUrl,
    loginPath: expectedResult.loginUrl,
    logoutPath: expectedResult.logoutUrl,
    impersonatePath: expectedResult.impersonateUrl,
    impersonateLogoutPath: expectedResult.impersonateLogoutUrl,
    rootPath: expectedResult.rootUrl,
  },
  recordActionUrl: sinon.stub().returns(expectedResult.recordActionUrl),
  resourceActionUrl: sinon.stub().returns(expectedResult.resourceActionUrl),
  bulkActionUrl: sinon.stub().returns(expectedResult.bulkActionUrl),
  urlBuilder: sinon.stub(),
  loginUrl: sinon.stub().returns(expectedResult.loginUrl),
  forgotPasswordUrl: sinon.stub().returns(expectedResult.forgotPasswordUrl),
  signupUrl: sinon.stub().returns(expectedResult.signupUrl),
  changePasswordUrl: sinon.stub().returns(expectedResult.changePasswordUrl),
  impersonateUrl: sinon.stub().returns(expectedResult.impersonateUrl),
  impersonateLogoutUrl: sinon.stub().returns(expectedResult.impersonateLogoutUrl),
  logoutUrl: sinon.stub().returns(expectedResult.logoutUrl),
  assetPath: sinon.stub().returns(expectedResult.assetPath),
  resourceUrl: sinon.stub().returns(expectedResult.resourceUrl),
  dashboardUrl: sinon.stub().returns(expectedResult.dashboardUrl),
  pageUrl: sinon.stub().returns(expectedResult.pageUrl),
  publicPageUrl: sinon.stub().returns(expectedResult.publicPageUrl),
  editUrl: sinon.stub().returns(expectedResult.editUrl),
  showUrl: sinon.stub().returns(expectedResult.showUrl),
  deleteUrl: sinon.stub().returns(expectedResult.deleteUrl),
  newUrl: sinon.stub().returns(expectedResult.newUrl),
  listUrl: sinon.stub().returns(expectedResult.listUrl),
  bulkDeleteUrl: sinon.stub().returns(expectedResult.bulkDeleteUrl),
});

module.exports.expectedResult = expectedResult;
